In [1]:
print("this is my first")

this is my first


In [4]:
print("this is my first")

this is my first


In [6]:
list1=[2,3,4,10]
arr1=np.array(list1)
arr1

NameError: name 'np' is not defined

In [8]:
arr1

NameError: name 'arr1' is not defined

In [10]:
import numpy as np
list1=[2,3,4,10]
arr1=np.array(list1)
arr1

array([ 2,  3,  4, 10])

In [12]:
type(list1)
type(arr1)

numpy.ndarray

In [14]:
type(list1)

list

In [16]:
#in case of numpy array we can apply vectorised operations.
#list mai vectorised opertions nhi perform kr sakte
#list1+1 ->error
arr1+1

array([ 3,  4,  5, 11])

In [18]:
#array from 2d list
list2d=[[9,0,4,6],[4,6,2,1]]
arr2=np.array(list2)

NameError: name 'list2' is not defined

In [20]:
arr2=np.array(list2d)

In [22]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [24]:
#numpy arrays to float vlues
#float array
arr2=np.array(list2,dtype='float')
arr2


NameError: name 'list2' is not defined

In [26]:
arr_float=np.array(list2d,dtype='float')
arr_float

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [28]:
arr3=arr2.astype('int')
arr3

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [30]:
#astype->to convert to integer type


In [32]:
#bool array
arr_bool=np.array(list2d,dtype='bool')
arr_bool

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
#object array
arr5=np.array([2,5,2.0,'y'],dtype='object')
arr5

array([2, 5, 2.0, 'y'], dtype=object)

In [36]:
arr5

array([2, 5, 2.0, 'y'], dtype=object)

In [38]:
#array to list function
list3=arr5.tolist()

In [40]:
type(list3)

list

In [42]:
type(arr5)

numpy.ndarray

In [44]:
#array dimensions
#shape of numpy array
list2d

[[9, 0, 4, 6], [4, 6, 2, 1]]

In [46]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [48]:
arr2.shape

(2, 4)

In [50]:
#total no of elements in array
arr2.size

8

In [52]:
arr2.dtype

dtype('int32')

In [54]:
#dimensions
arr2.ndim

2

In [56]:
#reversing rows and columns
#reversing rows
arr2[::-1]

array([[4, 6, 2, 1],
       [9, 0, 4, 6]])

In [58]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [60]:
#reversing columns
arr2(::-1,::-1)


SyntaxError: invalid syntax (3118271021.py, line 2)

In [62]:
arr2[::-1,::-1]

array([[1, 2, 6, 4],
       [6, 4, 0, 9]])

In [64]:
#specific element extraction
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [66]:
#excess the element present in first row
arr2[0,:]

array([9, 0, 4, 6])

In [68]:
arr2[:1,:]


array([[9, 0, 4, 6]])

In [70]:
#it should return 0,1 rows and all elements in rows 0,1
arr2[:2,:]

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [72]:
arr2[:-1,:]

array([[9, 0, 4, 6]])

In [74]:
arr2d=[[1,2,3,4],[3,3,21,1],[2,3,2,1]]
arr2d

[[1, 2, 3, 4], [3, 3, 21, 1], [2, 3, 2, 1]]

In [76]:
array_2d=np.arr(arr2d)

AttributeError: module 'numpy' has no attribute 'arr'

In [78]:
array_2d=np.array(arr2d)

In [80]:
array_2d

array([[ 1,  2,  3,  4],
       [ 3,  3, 21,  1],
       [ 2,  3,  2,  1]])

In [82]:
array_2d[:-1,:]
#all rows except last one

array([[ 1,  2,  3,  4],
       [ 3,  3, 21,  1]])

In [84]:
array_2d[:2,:]

array([[ 1,  2,  3,  4],
       [ 3,  3, 21,  1]])

In [86]:
array_2d[:3,:]

array([[ 1,  2,  3,  4],
       [ 3,  3, 21,  1],
       [ 2,  3,  2,  1]])

In [88]:
array_2d[:2,:3]

array([[ 1,  2,  3],
       [ 3,  3, 21]])

In [90]:
array_2d[:3,:1]

array([[1],
       [3],
       [2]])

In [92]:
array_2d[:,3]

array([4, 1, 1])

In [94]:
array_2d[:2,1]

array([2, 3])

In [96]:
array_2d[:1,:]

array([[1, 2, 3, 4]])

In [98]:
array_2d[:1,:2]

array([[1, 2]])

In [100]:
array_2d[:2,3]

array([4, 1])

In [102]:
array_2d


array([[ 1,  2,  3,  4],
       [ 3,  3, 21,  1],
       [ 2,  3,  2,  1]])

In [104]:
#columns
array_2d[:3,3]

array([4, 1, 1])

In [106]:
array_2d[:2,3]

array([4, 1])

In [108]:
array_2[1:2,3]

NameError: name 'array_2' is not defined

In [110]:
array_2d[1:2,3]

array([1])

In [112]:
array_2d[1:2,1:2]

array([[3]])

In [114]:
array_2d[1:2,:-1]

array([[ 3,  3, 21]])

In [116]:
array_2d[1:2,-1:]

array([[1]])

In [118]:
#array_2d[start:endofrow,start:endofcol]
array_2d

array([[ 1,  2,  3,  4],
       [ 3,  3, 21,  1],
       [ 2,  3,  2,  1]])

In [120]:
array_2d[1:2,-4:-1]

array([[ 3,  3, 21]])

In [122]:
array_2d[1:2,-4:]

array([[ 3,  3, 21,  1]])

In [124]:
#basic stats
#minimum 
array_2d.min()

1

In [126]:
array_2d.max()

21

In [128]:
arr2.sum()

32

In [130]:
np.median(arr2)

4.0

In [132]:
np.median(array_2d)

2.5

In [134]:
np.average(arr2)

4.0

In [136]:
np.var(arr2)

7.75

In [138]:
#reshaping and flattening
array_2d

array([[ 1,  2,  3,  4],
       [ 3,  3, 21,  1],
       [ 2,  3,  2,  1]])

In [140]:
array_2d.reshape(4,2)


ValueError: cannot reshape array of size 12 into shape (4,2)

In [142]:
array_2d.shape()


TypeError: 'tuple' object is not callable

In [144]:
arr2.shape()


TypeError: 'tuple' object is not callable

In [146]:
arr2.shape()

TypeError: 'tuple' object is not callable

In [148]:
arr2.shape

(2, 4)

In [150]:
arr2.reshape(4,2)

array([[9, 0],
       [4, 6],
       [4, 6],
       [2, 1]])

In [152]:
#1 row and 8 columns mai reshape karna hai
arr2.reshape(1,8)

array([[9, 0, 4, 6, 4, 6, 2, 1]])

In [154]:
arr2.reshape(4,4)

ValueError: cannot reshape array of size 8 into shape (4,4)

In [156]:
arr2.shape(8,1)

TypeError: 'tuple' object is not callable

In [158]:
arr2.reshape(8,1)

array([[9],
       [0],
       [4],
       [6],
       [4],
       [6],
       [2],
       [1]])

In [160]:
#flatten functipns flattens the arry
f1=arr2.flatten()

In [162]:
f1.ndim

1

In [164]:
arr2.ndim

2

In [166]:
#creating random arrays and sequences
ap.arange(10)

NameError: name 'ap' is not defined

In [168]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [174]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [176]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [178]:
#linspace function
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [180]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [182]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [184]:
#the stepsize is auto adjusted according to the no of elements
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [186]:
#zeros function returns array element equal to 0
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [188]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [190]:
np.zeros([2,3,4])
#3d array it is

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [192]:
#unique items and count
arr=[[1,4,5,2,2,5],[4,4,1,7,4,5]]

In [194]:
arr


[[1, 4, 5, 2, 2, 5], [4, 4, 1, 7, 4, 5]]

In [196]:
u_val,count=np.unique(arr,return_counts=True)
u_val

array([1, 2, 4, 5, 7])

In [198]:
count

array([2, 2, 4, 3, 1], dtype=int64)

In [ ]:
import pandas as pd
